### ISSUE TITLE
Which is the difference between var, let and cons? 

### ISSUE THREAD

**Issue by politologu** [jadjoubran/codetogo.io#10]

**Comment by kissu** [comment]
[MDN Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Declarations)

**Comment by politologu** [comment]
@kissu I know the answer to that question :) but I am going to suggest @jadjoubran to put on web :) is important!

**Comment by kissu** [comment]
I'm sure you do but I made the things faster for jad by giving him the MDN links. See no offense here. 🙏

**Comment by politologu** [comment]
no problem :)!

**Comment by jadjoubran** [comment]
Thanks @politologu for opening the issue!
At the moment we're only posting use cases (questions that begin with `how to`) rather than theoretical explanations which can be found in multiple websites
The way we're tackling this particular topic though (var, let & const) is by never using `var` in our examples as it's mostly recommended to use `let` and `const`.

We also have this use case:
[How to define a variable in JavaScript](https://codetogo.io/how-to-define-variable-in-javascript/)

Feel free to re-open this issue or create a new one if you've got additional suggestions
