### ISSUE TITLE
Use Case Suggestion: Get the style value of a particular element in the DOM

### ISSUE THREAD

**Issue by OdinTech3** [jadjoubran/codetogo.io#117]
```css
div {
color: white;
border: 1px solid black;
}
```

```html
<div id="ex-div"></div>
```

```javascript
const getStyle = (el) => window.getComputedStyle ? getComputedStyle(el, null) : el.currentStyle;

let div = document.querySelector('#ex-div');

console.log(getStyle(div).color) // => 'white';
```
The ``getStyle`` function returns the styles of an element and the values are read only, so you can't set them. 
In order to set the style of an element you would have to use ``div.style```

**Comment by jadjoubran** [comment]
Awesome!
This would be **related** to [How to change CSS property in JavaScript](https://codetogo.io/how-to-change-css-property-in-javascript/) right? Since yours is about reading, the other one is about changing

Browser support for getComputedStyle, is there a point in checking for its browser support and falling back for currentStyle (which turns out to be a proprietary feature only available in IE)?

[element.currentStyle](https://developer.mozilla.org/en-US/docs/Web/API/Element/currentStyle)

<img width="721" alt="screen shot 2018-03-15 at 5 37 22 pm" src="https://user-images.githubusercontent.com/2265232/37473784-98655398-2877-11e8-8fab-834de4582108.png">
<img width="1264" alt="screen shot 2018-03-15 at 5 35 13 pm" src="https://user-images.githubusercontent.com/2265232/37473790-9a8d7c18-2877-11e8-9221-6a01676d6e3d.png">

**Comment by jadjoubran** [comment]
Other than that please feel free to submit a PR 😄

**Comment by OdinTech3** [comment]
Refs pull request [143](https://github.com/jadjoubran/codetogo.io/pull/143)

**Comment by jadjoubran** [comment]
🎬 [How to get CSS property in JavaScript](https://codetogo.io/how-to-get-css-property-in-javascript/)
