### ISSUE TITLE
Use Case Suggestion: How to Flatten array

### ISSUE THREAD

**Issue by elatfy** [jadjoubran/codetogo.io#14]
Use Array.reduce() to get all elements inside the array and concat() to flatten them.

```javascript
const flatten = arr => arr.reduce((a, v) => a.concat(v), []);
// flatten([1,[2],3,4]) -> [1,2,3,4]
```

**Comment by jadjoubran** [comment]
Thanks @elatfy!
The problem is that this doesn't work in all scenarios, for example:

```
let arr = [1,[2],[[3]],4];
```

I remember that was a repository on github with snippets of javascript that can do pretty much what lodash can do but without any library.. I can't remember the name though

But I'm also not sure if we should go that route since we're trying to cover the kind of use cases that are not properly covered on other websites (or those that can be simplified)

**Comment by kakadiadarpan** [comment]
How about this? This takes care of nested arrays as well.

```
const flatten = (nestedArray) =>
  nestedArray.reduce((flattenedArray, item) =>
    flattenedArray.concat(Array.isArray(item) ? flatten(item) : [item]), []);
```

**Comment by jadjoubran** [comment]
thanks @kakadiadarpan 
This works indeed!

**Comment by kakadiadarpan** [comment]
@jadjoubran Should I create a PR for this?

**Comment by jadjoubran** [comment]
@kakadiadarpan yeah sure! 
Please keep it procedural style, similarly to all the use cases on codetogo, for example: [How to convert from degree to radian in JavaScript](https://codetogo.io/how-to-convert-from-degree-to-radian-in-javascript/)
rather than creating a reusable function, simply list the steps that alow you to transform the original input (in our case `[1, [2], 3, 4]` into a flattened array)
Even though people will eventually use it as a function, the aim of codetogo is not to push people to `copy paste` code, we rather want them to learn, that's why we list instructions step by step
This is also a key differentiation between other awesome repos (such as https://github.com/Chalarangelo/30-seconds-of-code)

Feel free to submit the PR even if you're not 100% sure that it's correct, I will help you with comments 😄 
thanks for your time!

**Comment by jadjoubran** [comment]
thanks to @elatfy & @kakadiadarpan 
🎬 [How to flatten a nested array in JavaScript](https://codetogo.io/how-to-flatten-a-nested-array-in-javascript/)
