### ISSUE TITLE
Use Case Suggestion: thousandSeperator

### ISSUE THREAD

**Issue by theIYD** [jadjoubran/codetogo.io#49]
**_function thousandSeperator_**: Seperate thousands using commas

```js
const thousandSeperator = (num) => {
    let parts = num.toString().split(".");
    parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    return parts.join(".");
}

console.log(thousandSeperator(130000));
//=> 130,000
```

Reference: https://goo.gl/jKeiy8

Thanks @jadjoubran 😊

**Comment by jadjoubran** [comment]
Thanks @theIYD 
This is a bit big and has the same situation as #18 
so I'll keep it open with the label `later` when we see how codetogo evolves

**Comment by theIYD** [comment]
Cool ! 

Does Code To Go need one liner solutions specifically as of now ?

**Comment by jadjoubran** [comment]
Not necessarily one liner solutions, for example [How to fetch json in JavaScript](https://codetogo.io/how-to-fetch-json-in-javascript/) and other use cases are more than one line, however they're tackling a single use case, rather than a ready made function.

The reason why I'm avoiding functions is because [30-seconds-of-code](https://github.com/Chalarangelo/30-seconds-of-code) has most of these covered

**Comment by theIYD** [comment]
<a href="https://github.com/Chalarangelo/30-seconds-of-code">30-seconds-of-code</a> has one liner solutions (most of them). Of course there is a noticeable difference between the two. 

Will be posting more use cases. 😊👍

**Comment by jadjoubran** [comment]
yes indeed, the problem is if you take a look at this example:

```
const flattenDepth = (arr, depth = 1) =>
  depth != 1 ? arr.reduce((a, v) => a.concat(Array.isArray(v) ? flattenDepth(v, depth - 1) : v), [])
  : arr.reduce((a, v) => a.concat(v), []);
```

you can immediately understand what the function does but reading what's happening inside the function takes a lot more time

And awesome thanks 😄
