### ISSUE TITLE
Use Case Suggestion: How to combine array properties into one array in an array of objects

### ISSUE THREAD

**Issue by hozzjss** [jadjoubran/codetogo.io#58]
```
function extractAndCombineArrays(objectsHasArrayArray, arrayPropName) {
  return objectsHasArrayArray.map(obj => obj[arrayPropName])
    .reduce((allArrays, nextArray) => allArrays.concat(nextArray));
}
```

**Comment by jadjoubran** [comment]
Thanks @hozzjss 
Is this similar to [How to concatenate arrays in JavaScript](https://codetogo.io/how-to-concatenate-arrays-in-javascript/) with the addition of extracting properties from array?

**Comment by hozzjss** [comment]
@jadjoubran
yes kinda
the rest operator might be clearer though 
the difference is that you extract a group of arrays from a group of objects one example might be this
```
const branchManagers = [
  {
    "name": "Jake",
    "branches": [
      "Cairo, Downtown",
      "Cairo airport",
    ]
  },
  {
    "name": "John",
    "branches": [
      "Alexandria, Coast",
      "Alexandria, City",
    ]
  },
];
const allBranches = extractAndCombineArrays(branchManagers, 'branches');
```

**Comment by jadjoubran** [comment]
okay makes sense
This would be a bit too complicated though compared to the use cases we're showing on the website
Codetogo is mainly for simple/isolated use cases so that's why we're not adding `functions` that you can copy paste as there are other awesome repos/projects for that

Feel free to re-open or create a new issue for new use cases, thanks! 😄
