### ISSUE TITLE
How to detect the the visitor's browser and os type

### ISSUE THREAD

**Issue by BrahimS** [jadjoubran/codetogo.io#80]
```javaScript
const browserName = window.navigator.appName;
const osName = window.navigator.platform;
```

**Comment by jadjoubran** [comment]
Hi @BrahimS 
Thanks for suggesting this use case!
Unfortunately `window.navigator.appName` is deprecated (check [MDN](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/appName))
and `window.navigator.platform` returns all sorts of results rather than simply **the operating system name** (see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/platform) and [stackoverflow question](https://stackoverflow.com/questions/19877924/what-is-the-list-of-possible-values-for-navigator-platform-as-of-today))

I'm going to close this issue but feel free to re-open if you think it's worth reconsidering or if you've got additional information that may help
And I'd love to see other use cases so thanks for your time and looking forward for more contributions 😄

**Comment by BrahimS** [comment]
Hi @jadjoubran Thanks for the links, very instructive. 💯

**Comment by jadjoubran** [comment]
No worries @BrahimS 
I'm glad that's useful 😄
